import type { CurrentState } from '../../types/case'

export const currentState = {
  headline:
    'Carrier operations remain highly phone-driven even though most of the information required to complete the interaction already exists digitally.',
  metrics: [
    {
      id: 'calls-per-day',
      label: 'Carrier calls / day',
      value: 1200,
      unit: 'calls',
      format: 'number',
      timeframe: 'day',
      prominence: 'hero',
      sourceId: 'atlas-placeholder-metrics',
      provenance: 'our-design',
      confidence: 'placeholder',
    },
    {
      id: 'carrier-reps',
      label: 'Carrier reps',
      value: 35,
      unit: 'people',
      format: 'number',
      prominence: 'primary',
      sourceId: 'atlas-placeholder-metrics',
      provenance: 'our-design',
      confidence: 'placeholder',
    },
    {
      id: 'aht-minutes',
      label: 'Average handling time',
      value: 5.8,
      unit: 'min',
      format: 'duration',
      timeframe: 'interaction',
      prominence: 'primary',
      sourceId: 'atlas-placeholder-metrics',
      provenance: 'our-design',
      confidence: 'placeholder',
    },
    {
      id: 'abandonment-rate',
      label: 'Abandonment rate',
      value: 0.14,
      unit: '%',
      format: 'percent',
      prominence: 'secondary',
      sourceId: 'atlas-placeholder-metrics',
      provenance: 'our-design',
      confidence: 'placeholder',
    },
    {
      id: 'after-hours-share',
      label: 'After-hours call share',
      value: 0.18,
      unit: '%',
      format: 'percent',
      prominence: 'secondary',
      sourceId: 'atlas-placeholder-metrics',
      provenance: 'our-design',
      confidence: 'placeholder',
    },
    {
      id: 'systems-touched',
      label: 'Systems touched per call',
      value: { min: 3, max: 4 },
      unit: 'systems',
      format: 'range',
      prominence: 'secondary',
      sourceId: 'atlas-placeholder-metrics',
      provenance: 'our-design',
      confidence: 'placeholder',
    },
  ],
  clusters: [
    {
      id: 'people',
      label: 'People',
      metricIds: ['carrier-reps'],
      summary: 'Carrier sales reps and supporting operations roles.',
    },
    {
      id: 'volume',
      label: 'Volume',
      metricIds: ['calls-per-day', 'abandonment-rate', 'after-hours-share'],
      summary: 'Inbound demand and service pressure.',
    },
    {
      id: 'systems',
      label: 'Systems',
      metricIds: ['systems-touched', 'aht-minutes'],
      summary: 'Operational systems touched during routine handling.',
    },
  ],
} satisfies CurrentState
