import type { SolutionDesign } from '../../types/solution'

const evidence = {
  provenance: 'our-design' as const,
  confidence: 'placeholder' as const,
  sourceId: 'atlas-placeholder-solution',
}

/**
 * Atlas Freight fictional solution — labels are case-specific;
 * IDs stay reusable for Phase 4 event streams.
 */
export const solution = {
  businessObjective: {
    id: 'obj-routine-orchestration',
    statement:
      'Orchestrate routine inbound carrier interactions end-to-end while preserving verification, authorized pricing, booking confirmation, and escalation quality.',
    rationale:
      'Automating conversation alone does not remove the integration burden diagnosed in the current state.',
  },
  targetOutcomes: [
    {
      id: 'out-resolve-routine',
      label: 'Resolve routine interactions without human integration work',
      description:
        'Verification, retrieval, authorized quoting, and booking complete through orchestration when policy allows.',
    },
    {
      id: 'out-escalate-intact',
      label: 'Escalate exceptions with context intact',
      description:
        'Humans receive judgment-heavy cases with the operational state already assembled.',
    },
  ],
  operatingModel: {
    beforeLabel: 'Actor → Human → Systems',
    afterLabel: 'Actor → HappyRobot → Systems',
    humanRoleLabel: 'Humans own exceptions',
    beforeSummary:
      'People retrieve context, apply judgment, and write outcomes across fragmented systems.',
    afterSummary:
      'HappyRobot orchestrates routine context, tools, and actions; humans retain high-judgment exceptions.',
  },
  channels: [
    {
      id: 'channel-voice',
      label: 'Carrier voice interaction',
      type: 'voice',
      description: 'Primary inbound channel for carrier booking requests.',
      primary: true,
      ...evidence,
    },
    {
      id: 'channel-sms',
      label: 'SMS confirmation',
      type: 'sms',
      description: 'Optional output channel for confirmations — not a core operational system.',
      ...evidence,
    },
    {
      id: 'channel-email',
      label: 'Email confirmation',
      type: 'email',
      description: 'Optional output channel for confirmations — not a core operational system.',
      ...evidence,
    },
  ],
  contextSources: [
    {
      id: 'ctx-party-identity',
      label: 'Caller / carrier identity',
      description: 'Who is calling and how they map to a known carrier account.',
      systemId: 'carrier-qualification',
      fields: ['carrierId', 'accountStatus', 'verificationState'],
      relatedProcessStepIds: ['identify-carrier'],
      relatedBottleneckIds: ['bn-information-retrieval', 'bn-system-fragmentation'],
      ...evidence,
    },
    {
      id: 'ctx-qualification',
      label: 'Qualification / compliance status',
      description: 'Eligibility and compliance posture before load-specific disclosure.',
      systemId: 'carrier-qualification',
      fields: ['eligible', 'restrictions', 'complianceFlags'],
      relatedProcessStepIds: ['check-eligibility'],
      relatedBottleneckIds: ['bn-information-retrieval'],
      ...evidence,
    },
    {
      id: 'ctx-work-item',
      label: 'Load identifier & details',
      description: 'Load reference, lane, equipment, and schedule windows.',
      systemId: 'tms',
      fields: ['loadId', 'lane', 'equipment', 'pickupWindow', 'deliveryWindow'],
      relatedProcessStepIds: ['identify-load', 'check-availability'],
      relatedBottleneckIds: ['bn-information-retrieval'],
      ...evidence,
    },
    {
      id: 'ctx-work-item-status',
      label: 'Load status',
      description: 'Whether the load remains available for booking.',
      systemId: 'tms',
      fields: ['status', 'available'],
      relatedProcessStepIds: ['check-availability'],
      ...evidence,
    },
    {
      id: 'ctx-commercial-params',
      label: 'Authorized pricing parameters',
      description: 'Approved rate / band from the system of record — not invented in conversation.',
      systemId: 'tms',
      fields: ['authorizedRate', 'rateBand'],
      relatedProcessStepIds: ['retrieve-rate', 'negotiate-confirm'],
      relatedBottleneckIds: ['bn-information-retrieval'],
      ...evidence,
    },
    {
      id: 'ctx-interaction-state',
      label: 'Prior interaction state',
      description: 'Relevant CRM history when it affects continuity of the conversation.',
      systemId: 'crm',
      fields: ['lastInteraction', 'openNotes'],
      relatedProcessStepIds: ['update-records'],
      ...evidence,
    },
  ],
  stages: [
    {
      id: 'stage-understand-intent',
      label: 'Understand intent',
      description:
        'Interpret the caller request and decide which bounded workflow applies.',
      controlMode: 'agentic',
      relatedDecisionIds: ['decision-enough-context', 'decision-next-action'],
      relatedProcessStepIds: ['receive-request'],
      relatedBottleneckIds: ['bn-information-retrieval'],
      ...evidence,
    },
    {
      id: 'stage-assemble-context',
      label: 'Assemble operational context',
      description:
        'Retrieve identity, eligibility, load, and pricing context through deterministic tools.',
      controlMode: 'deterministic',
      relatedToolIds: [
        'identify-party',
        'retrieve-work-item',
        'check-eligibility',
        'retrieve-authorized-rate',
      ],
      relatedNorthstarIds: ['ns-verify-before-disclosure', 'ns-authorized-rate-source'],
      relatedProcessStepIds: [
        'identify-carrier',
        'identify-load',
        'check-eligibility',
        'check-availability',
        'retrieve-rate',
      ],
      relatedBottleneckIds: ['bn-information-retrieval', 'bn-system-fragmentation'],
      ...evidence,
    },
    {
      id: 'stage-bounded-negotiation',
      label: 'Bounded negotiation',
      description:
        'Conduct conversational negotiation only inside authorized commercial parameters.',
      controlMode: 'agentic',
      relatedDecisionIds: ['decision-within-policy'],
      relatedToolIds: ['retrieve-authorized-rate'],
      relatedNorthstarIds: ['ns-authorized-rate-source', 'ns-compliance-escalation'],
      relatedProcessStepIds: ['negotiate-confirm'],
      ...evidence,
    },
    {
      id: 'stage-execute-outcome',
      label: 'Execute outcome',
      description:
        'Commit booking, write records, and send confirmation when confirmation is explicit.',
      controlMode: 'deterministic',
      relatedToolIds: [
        'book-work-item',
        'update-interaction-record',
        'send-confirmation',
      ],
      relatedNorthstarIds: [
        'ns-explicit-booking-confirmation',
        'ns-system-of-record-integrity',
      ],
      relatedProcessStepIds: ['book-carrier', 'update-records', 'send-confirmation'],
      relatedBottleneckIds: ['bn-manual-writeback'],
      ...evidence,
    },
    {
      id: 'stage-route-exception',
      label: 'Route exception',
      description: 'Hand off to humans when policy, identity, compliance, or systems block autonomy.',
      controlMode: 'human',
      relatedToolIds: ['escalate-to-human'],
      relatedNorthstarIds: ['ns-compliance-escalation'],
      relatedBottleneckIds: ['bn-human-availability'],
      ...evidence,
    },
  ],
  decisionPoints: [
    {
      id: 'decision-enough-context',
      label: 'Enough trusted context?',
      description: 'Decide whether identity and load references are clear enough to proceed.',
      controlMode: 'agentic',
      conditionSummary: 'Ambiguous party or work-item references block disclosure and booking.',
      outcomes: [
        { id: 'out-proceed', label: 'Proceed to retrieve', nextId: 'stage-assemble-context' },
        { id: 'out-clarify', label: 'Clarify with caller', nextId: 'stage-understand-intent' },
        {
          id: 'out-escalate-ambiguous',
          label: 'Escalate ambiguous case',
          nextId: 'esc-ambiguous-work-item',
        },
      ],
      relatedNorthstarIds: ['ns-verify-before-disclosure'],
      ...evidence,
    },
    {
      id: 'decision-next-action',
      label: 'Next allowed action',
      description: 'Choose the next tool within policy after context is assembled.',
      controlMode: 'agentic',
      conditionSummary: 'Tool choice stays inside the configured workflow and Northstars.',
      outcomes: [
        { id: 'out-quote', label: 'Quote authorized rate', nextId: 'retrieve-authorized-rate' },
        { id: 'out-book', label: 'Seek booking confirmation', nextId: 'stage-execute-outcome' },
        { id: 'out-escalate', label: 'Escalate', nextId: 'escalate-to-human' },
      ],
      ...evidence,
    },
    {
      id: 'decision-within-policy',
      label: 'Within authorized policy?',
      description: 'Detect requests outside the approved rate band or compliance boundary.',
      controlMode: 'agentic',
      conditionSummary: 'Out-of-band commercial or compliance conditions escalate.',
      outcomes: [
        { id: 'out-continue', label: 'Continue in band', nextId: 'stage-execute-outcome' },
        { id: 'out-rate-esc', label: 'Escalate rate exception', nextId: 'esc-rate-out-of-band' },
        {
          id: 'out-compliance-esc',
          label: 'Escalate compliance',
          nextId: 'esc-compliance-restricted',
        },
      ],
      relatedNorthstarIds: ['ns-authorized-rate-source', 'ns-compliance-escalation'],
      ...evidence,
    },
  ],
  tools: [
    {
      id: 'identify-party',
      label: 'Identify party',
      description: 'Verify caller identity against the qualification / compliance system.',
      systemId: 'carrier-qualification',
      access: 'read',
      controlMode: 'deterministic',
      relatedNorthstarIds: ['ns-verify-before-disclosure'],
      relatedProcessStepIds: ['identify-carrier'],
      relatedBottleneckIds: ['bn-information-retrieval'],
      ...evidence,
    },
    {
      id: 'retrieve-work-item',
      label: 'Retrieve work item',
      description: 'Look up the load and operational details in the TMS.',
      systemId: 'tms',
      access: 'read',
      controlMode: 'deterministic',
      relatedNorthstarIds: ['ns-verify-before-disclosure'],
      relatedProcessStepIds: ['identify-load', 'check-availability'],
      relatedBottleneckIds: ['bn-information-retrieval'],
      ...evidence,
    },
    {
      id: 'check-eligibility',
      label: 'Check eligibility',
      description: 'Evaluate carrier eligibility against explicit qualification rules.',
      systemId: 'carrier-qualification',
      access: 'read',
      controlMode: 'deterministic',
      relatedNorthstarIds: ['ns-verify-before-disclosure', 'ns-compliance-escalation'],
      relatedProcessStepIds: ['check-eligibility'],
      relatedBottleneckIds: ['bn-system-fragmentation'],
      ...evidence,
    },
    {
      id: 'retrieve-authorized-rate',
      label: 'Retrieve authorized rate',
      description: 'Read the approved rate / band from the system of record.',
      systemId: 'tms',
      access: 'read',
      controlMode: 'deterministic',
      relatedNorthstarIds: ['ns-authorized-rate-source'],
      relatedProcessStepIds: ['retrieve-rate'],
      relatedBottleneckIds: ['bn-information-retrieval'],
      ...evidence,
    },
    {
      id: 'book-work-item',
      label: 'Book work item',
      description: 'Commit the booking in the TMS after explicit confirmation.',
      systemId: 'tms',
      access: 'write',
      controlMode: 'deterministic',
      relatedNorthstarIds: [
        'ns-explicit-booking-confirmation',
        'ns-system-of-record-integrity',
      ],
      relatedProcessStepIds: ['book-carrier'],
      relatedBottleneckIds: ['bn-manual-writeback'],
      ...evidence,
    },
    {
      id: 'update-interaction-record',
      label: 'Update interaction record',
      description: 'Write interaction outcome into CRM / history.',
      systemId: 'crm',
      access: 'write',
      controlMode: 'deterministic',
      relatedNorthstarIds: ['ns-system-of-record-integrity'],
      relatedProcessStepIds: ['update-records'],
      relatedBottleneckIds: ['bn-manual-writeback'],
      ...evidence,
    },
    {
      id: 'send-confirmation',
      label: 'Send confirmation',
      description:
        'Notify the carrier of the confirmed outcome via SMS/email output channels.',
      access: 'notify',
      controlMode: 'deterministic',
      relatedNorthstarIds: ['ns-system-of-record-integrity'],
      relatedProcessStepIds: ['send-confirmation'],
      relatedBottleneckIds: ['bn-manual-writeback'],
      ...evidence,
    },
    {
      id: 'escalate-to-human',
      label: 'Escalate to human',
      description: 'Create a human handoff with assembled context.',
      access: 'escalate',
      controlMode: 'human',
      relatedNorthstarIds: ['ns-compliance-escalation'],
      relatedBottleneckIds: ['bn-human-availability'],
      ...evidence,
    },
  ],
  actions: [
    {
      id: 'action-disclose-work-item',
      label: 'Disclose work-item details',
      description: 'Share load-specific information only after verification.',
      toolId: 'retrieve-work-item',
      systemId: 'tms',
      controlMode: 'deterministic',
      relatedNorthstarIds: ['ns-verify-before-disclosure'],
      ...evidence,
    },
    {
      id: 'action-quote-rate',
      label: 'Communicate authorized rate',
      description: 'Quote only from the authorized system source.',
      toolId: 'retrieve-authorized-rate',
      systemId: 'tms',
      controlMode: 'deterministic',
      relatedNorthstarIds: ['ns-authorized-rate-source'],
      ...evidence,
    },
    {
      id: 'action-commit-booking',
      label: 'Commit booking',
      description: 'Write the booking after explicit carrier confirmation.',
      toolId: 'book-work-item',
      systemId: 'tms',
      controlMode: 'deterministic',
      relatedNorthstarIds: ['ns-explicit-booking-confirmation'],
      ...evidence,
    },
    {
      id: 'action-send-confirmation',
      label: 'Send confirmation',
      description: 'Deliver confirmation through SMS/email output channels.',
      toolId: 'send-confirmation',
      channelIds: ['channel-sms', 'channel-email'],
      controlMode: 'deterministic',
      relatedNorthstarIds: ['ns-system-of-record-integrity'],
      ...evidence,
    },
    {
      id: 'action-handoff',
      label: 'Hand off to human',
      description: 'Transfer the interaction with context to the exception owner.',
      toolId: 'escalate-to-human',
      controlMode: 'human',
      relatedNorthstarIds: ['ns-compliance-escalation'],
      ...evidence,
    },
  ],
  escalationPaths: [
    {
      id: 'esc-identity-unverified',
      label: 'Identity cannot be verified',
      trigger: 'Party identity cannot be verified against trusted sources',
      destinationRole: 'Carrier ops / supervisor',
      contextTransferred: ['attemptedIdentity', 'callRecordingRef', 'toolsAttempted'],
      resumable: true,
      relatedNorthstarIds: ['ns-verify-before-disclosure'],
      relatedToolIds: ['identify-party', 'escalate-to-human'],
      ...evidence,
    },
    {
      id: 'esc-qualification-failure',
      label: 'Qualification failure',
      trigger: 'Carrier fails eligibility checks',
      destinationRole: 'Compliance / carrier ops',
      contextTransferred: ['carrierId', 'eligibilityResult'],
      resumable: false,
      relatedNorthstarIds: ['ns-compliance-escalation'],
      relatedToolIds: ['check-eligibility', 'escalate-to-human'],
      ...evidence,
    },
    {
      id: 'esc-compliance-restricted',
      label: 'Restricted / compliance exception',
      trigger: 'Restricted load type or compliance flag requires human judgment',
      destinationRole: 'Compliance specialist',
      contextTransferred: ['loadId', 'complianceFlags', 'requestedAction'],
      resumable: false,
      relatedNorthstarIds: ['ns-compliance-escalation'],
      relatedToolIds: ['escalate-to-human'],
      ...evidence,
    },
    {
      id: 'esc-rate-out-of-band',
      label: 'Rate outside authorized band',
      trigger: 'Caller requests commercial terms outside approved parameters',
      destinationRole: 'Pricing / commercial desk',
      contextTransferred: ['authorizedRate', 'requestedRate', 'loadId'],
      resumable: true,
      relatedNorthstarIds: ['ns-authorized-rate-source', 'ns-compliance-escalation'],
      relatedToolIds: ['retrieve-authorized-rate', 'escalate-to-human'],
      ...evidence,
    },
    {
      id: 'esc-ambiguous-work-item',
      label: 'Ambiguous work item',
      trigger: 'Load reference cannot be resolved confidently',
      destinationRole: 'Carrier ops',
      contextTransferred: ['callerUtterance', 'candidateLoads'],
      resumable: true,
      relatedNorthstarIds: ['ns-verify-before-disclosure'],
      relatedToolIds: ['retrieve-work-item', 'escalate-to-human'],
      ...evidence,
    },
    {
      id: 'esc-system-unavailable',
      label: 'System unavailable',
      trigger: 'Required operational system is unavailable or returning errors',
      destinationRole: 'Carrier ops / supervisor',
      contextTransferred: ['failedSystemId', 'lastSuccessfulContext'],
      resumable: true,
      relatedToolIds: ['escalate-to-human'],
      ...evidence,
    },
    {
      id: 'esc-caller-requests-human',
      label: 'Caller requests human',
      trigger: 'Caller explicitly asks for a person',
      destinationRole: 'Carrier ops',
      contextTransferred: ['assembledContext', 'conversationSummary'],
      resumable: true,
      relatedToolIds: ['escalate-to-human'],
      ...evidence,
    },
  ],
} satisfies SolutionDesign
